### ISSUE TITLE
3694 - Usernames Unique - Cloning Attribute Resource Loop Runs Forever - occurs in chef-client 12.1.0+ [APPERS FIXED IN 12.3.0-1]

### ISSUE THREAD

**Issue by gyoza** [chef-cookbooks/users#94] opened 2015-04-14 20:09 UTC
Wondering if anybody here can help me figure out what is going on, so far my research shows that this is an issue with something that I am doing wrong.. (At least that is what irc thinks) heh..

Attempted to update one of my systems to chef 12.1.0+ and I am getting the following error(s) when trying to run the client. 

http://pastebin.com/p8Z1uaAm

I am not trying to do anything tricky. Simply using a databag named users with an enguser group set in the user json.

-Cookbook-

include_recipe 'users'

users_manage "engusers" do
  group_id 9001
  action [ :remove, :create ]
end

Not really sure how to resolve this since the attribute names appear to be unique?

To note, 12.0.3 does not exhibit this problem.

**Comment by gyoza** [comment] 2015-04-15 14:40
Trying to figure out if this is a problem with chef-client or a problem with the way I've done things in the recipe. So any ideas would be awesome! That way I can open the appropriate issue with whomever.

**Comment by QAFomalhaut** [comment] 2015-04-20 17:41
We have started running into this exact issue in the last few days as well. When the sysadmins recipe runs against a server that's already been provisioned with it, we're seeing an infinite loop. We are using the recipe in it's most basic form for sysadmin setup. We have a databag with user names and public keys, and call the recipe with include_recipe 'users::sysadmins'.

**Comment by gyoza** [comment] 2015-04-20 20:41
Thank god I am not the only one..
Also to note, during the infinite loop the CPU on the chef-client skyrockets. 

Can anybody here verify that the issue we're running into is a Chef Client Version issue or because of the following deprecated method for cloning resources?

https://tickets.opscode.com/browse/CHEF-3694

**Comment by thommay** [comment] 2015-05-07 14:59
I can't reproduce this using Chef 12.3.0 and 1.8.2 of the users cookbook:

```
Starting Chef Client, version 12.3.0
       [2015-05-07T14:55:51+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       resolving cookbooks for run list: ["tmp::default"]
       Synchronizing Cookbooks:
         - tmp
         - users
       Compiling Cookbooks...
       Converging 1 resources
       Recipe: tmp::default
         * users_manage[engusers] action remove (up to date)
         * users_manage[engusers] action create
           * user[user1] action create
             - create user user1
           * directory[/home/user1/.ssh] action create
             - create new directory /home/user1/.ssh
             - change mode from '' to '0700'
             - change owner from '' to 'user1'
             - change group from '' to 'user1'
           * user[user2] action create
             - create user user2
           * directory[/home/user2/.ssh] action create
             - create new directory /home/user2/.ssh
             - change mode from '' to '0700'
             - change owner from '' to 'user2'
             - change group from '' to 'user2'
           * user[user3] action create
             - create user user3
           * directory[/home/user3/.ssh] action create
             - create new directory /home/user3/.ssh
             - change mode from '' to '0700'
             - change owner from '' to 'user3'
             - change group from '' to 'user3'
           * user[user4] action create
             - create user user4
           * directory[/home/user4/.ssh] action create
             - create new directory /home/user4/.ssh
             - change mode from '' to '0700'
             - change owner from '' to 'user4'
             - change group from '' to 'user4'
           * group[engusers] action create
             - create engusers
```

Can you tell me what version of the users cookbook you're using?

**Comment by gyoza** [comment] 2015-05-07 19:10
Hello,

Thanks for looking into this, I am using 1.8.2.

I noticed that you didn't try to add any SSH keys, that is where the failure is occurring and may be why you're not able to reproduce. 

```
    - would create /home/user1/.ssh[2015-04-14T12:57:33-07:00] WARN: Cloning resource attributes for template[/home/user1/.ssh/authorized_keys] from prior resource (CHEF-3694)
```

**Comment by thommay** [comment] 2015-05-07 19:42
I actually tried it after with ssh keys too and it didn't change the result.

**Comment by gyoza** [comment] 2015-05-07 19:44
Thom,

After the initial creation did you attempt to run it again?

**Comment by gyoza** [comment] 2015-05-07 19:44
Also, I can try to use 12.3.0 later to see if anything has changed.. I will let you know.

**Comment by thommay** [comment] 2015-05-07 19:47
yep:
```
      Recipe: tmp::default
         * users_manage[engusers] action remove (up to date)
         * users_manage[engusers] action create
           * user[user1] action create (up to date)
           * directory[/home/user1/.ssh] action create (up to date)
           * template[/home/user1/.ssh/authorized_keys] action create (up to date)
           * user[user2] action create (up to date)
           * directory[/home/user2/.ssh] action create (up to date)
           * template[/home/user2/.ssh/authorized_keys] action create (up to date)
           * user[user3] action create (up to date)
           * directory[/home/user3/.ssh] action create (up to date)
           * template[/home/user3/.ssh/authorized_keys] action create (up to date)
           * user[user4] action create (up to date)
           * directory[/home/user4/.ssh] action create (up to date)
           * template[/home/user4/.ssh/authorized_keys] action create (up to date)
           * group[engusers] action create (up to date)
            (up to date)

       Running handlers:
       Running handlers complete
       Chef Client finished, 0/15 resources updated in 6.271626795 seconds
       Finished converging <default-ubuntu-1404> (0m9.18s).
-----> Kitchen is finished. (0m9.97s)
```
is a re-run. I'll try with chef 12.1.0 in a sec

**Comment by thommay** [comment] 2015-05-07 19:53
```
      Starting Chef Client, version 12.1.0
       Creating a new client identity for default-ubuntu-1404 using the validator key.
       [2015-05-07T19:51:48+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       [2015-05-07T19:51:48+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       resolving cookbooks for run list: ["tmp::default"]
       [2015-05-07T19:51:48+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       Synchronizing Cookbooks:
         - tmp
         - users
       Compiling Cookbooks...
       Converging 1 resources
       Recipe: tmp::default
         * users_manage[engusers] action remove (up to date)
         * users_manage[engusers] action create
           * user[user1] action create
             - create user user1
           * directory[/home/user1/.ssh] action create
             - create new directory /home/user1/.ssh
             - change mode from '' to '0700'
             - change owner from '' to 'user1'
             - change group from '' to 'user1'
           * template[/home/user1/.ssh/authorized_keys] action create
             - create new file /home/user1/.ssh/authorized_keys
             - update content in file /home/user1/.ssh/authorized_keys from none to b3c5a4
             --- /home/user1/.ssh/authorized_keys	2015-05-07 19:51:48.821259214 +0000
             +++ /tmp/chef-rendered-template20150507-1468-d368g	2015-05-07 19:51:48.821259214 +0000
             @@ -1 +1,6 @@
             +# Generated by Chef for default-ubuntu-1404
             +# Local modifications will be overwritten.
             +
             +ssh-rsa AAA123...xyz== foo
             +ssh-rsa AAA456...uvw== bar
             - change mode from '' to '0600'
             - change owner from '' to 'user1'
             - change group from '' to 'user1'
           * user[user2] action create
             - create user user2
           * directory[/home/user2/.ssh] action create
             - create new directory /home/user2/.ssh
             - change mode from '' to '0700'
             - change owner from '' to 'user2'
             - change group from '' to 'user2'
           * template[/home/user2/.ssh/authorized_keys] action create
             - create new file /home/user2/.ssh/authorized_keys
             - update content in file /home/user2/.ssh/authorized_keys from none to b3c5a4
             --- /home/user2/.ssh/authorized_keys	2015-05-07 19:51:48.869259212 +0000
             +++ /tmp/chef-rendered-template20150507-1468-1n1xmsl	2015-05-07 19:51:48.869259212 +0000
             @@ -1 +1,6 @@
             +# Generated by Chef for default-ubuntu-1404
             +# Local modifications will be overwritten.
             +
             +ssh-rsa AAA123...xyz== foo
             +ssh-rsa AAA456...uvw== bar
             - change mode from '' to '0600'
             - change owner from '' to 'user2'
             - change group from '' to 'user2'
           * user[user3] action create
             - create user user3
           * directory[/home/user3/.ssh] action create
             - create new directory /home/user3/.ssh
             - change mode from '' to '0700'
             - change owner from '' to 'user3'
             - change group from '' to 'user3'
           * template[/home/user3/.ssh/authorized_keys] action create
             - create new file /home/user3/.ssh/authorized_keys
             - update content in file /home/user3/.ssh/authorized_keys from none to b3c5a4
             --- /home/user3/.ssh/authorized_keys	2015-05-07 19:51:48.917259211 +0000
             +++ /tmp/chef-rendered-template20150507-1468-1cuno0b	2015-05-07 19:51:48.917259211 +0000
             @@ -1 +1,6 @@
             +# Generated by Chef for default-ubuntu-1404
             +# Local modifications will be overwritten.
             +
             +ssh-rsa AAA123...xyz== foo
             +ssh-rsa AAA456...uvw== bar
             - change mode from '' to '0600'
             - change owner from '' to 'user3'
             - change group from '' to 'user3'
           * user[user4] action create
             - create user user4
           * directory[/home/user4/.ssh] action create
             - create new directory /home/user4/.ssh
             - change mode from '' to '0700'
             - change owner from '' to 'user4'
             - change group from '' to 'user4'
           * template[/home/user4/.ssh/authorized_keys] action create
             - create new file /home/user4/.ssh/authorized_keys
             - update content in file /home/user4/.ssh/authorized_keys from none to b3c5a4
             --- /home/user4/.ssh/authorized_keys	2015-05-07 19:51:48.965259209 +0000
             +++ /tmp/chef-rendered-template20150507-1468-e7pgv8	2015-05-07 19:51:48.965259209 +0000
             @@ -1 +1,6 @@
             +# Generated by Chef for default-ubuntu-1404
       +# Local modifications will be overwritten.
             +
             +ssh-rsa AAA123...xyz== foo
       +ssh-rsa AAA456...uvw== bar
             - change mode from '' to '0600'
             - change owner from '' to 'user4'
             - change group from '' to 'user4'
           * group[engusers] action create
             - create group[engusers]


       Running handlers:
       Running handlers complete
       Chef Client finished, 14/15 resources updated in 6.923806547 seconds
       Finished converging <default-ubuntu-1404> (0m54.49s).
```
```
       Starting Chef Client, version 12.1.0
       [2015-05-07T19:53:03+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       resolving cookbooks for run list: ["tmp::default"]
       Synchronizing Cookbooks:
         - tmp
         - users
       Compiling Cookbooks...
       Converging 1 resources
       Recipe: tmp::default
         * users_manage[engusers] action remove (up to date)
         * users_manage[engusers] action create
           * user[user1] action create (up to date)
           * directory[/home/user1/.ssh] action create (up to date)
           * template[/home/user1/.ssh/authorized_keys] action create (up to date)
           * user[user2] action create (up to date)
           * directory[/home/user2/.ssh] action create (up to date)
           * template[/home/user2/.ssh/authorized_keys] action create (up to date)
           * user[user3] action create (up to date)
           * directory[/home/user3/.ssh] action create (up to date)
           * template[/home/user3/.ssh/authorized_keys] action create (up to date)
           * user[user4] action create (up to date)
           * directory[/home/user4/.ssh] action create (up to date)
           * template[/home/user4/.ssh/authorized_keys] action create (up to date)
           * group[engusers] action create (up to date)
            (up to date)

       Running handlers:
       Running handlers complete
       Chef Client finished, 0/15 resources updated in 6.281031646 seconds
       Finished converging <default-ubuntu-1404> (0m10.09s).
-----> Kitchen is finished. (0m10.76s)
```

so there must be something else going on. can you post a sample of your users data bag?

**Comment by thommay** [comment] 2015-05-07 19:54
and also how many items you have in the data bag?

**Comment by gyoza** [comment] 2015-05-07 20:06
action
comment
groups [0,1]
id
password
ssh_keys
uid

**Comment by gyoza** [comment] 2015-05-07 20:06
To note, we have multiple ssh keys per user.

**Comment by thommay** [comment] 2015-05-07 20:11
yeah, these runs have multiple ssh keys. How many items are there in your users data bag?

**Comment by gyoza** [comment] 2015-05-07 20:37
There are 11 users within the "users" databag

**Comment by gyoza** [comment] 2015-05-07 20:40
Soo, i just updated to 12.3.0-1 and its no longer happening..

**Comment by gyoza** [comment] 2015-05-07 20:46
I downgraded a machine to 12.1.0-1 and was able to reproduce the issue. Looks like somebody fixed something in 12.3.0.

**Comment by gyoza** [comment] 2015-05-07 21:01
@QAFomalhaut  Can you see if installing 12.3.0-1 fixes it for you as well? pretty pretty please?:)

**Comment by abriel** [comment] 2015-05-19 11:04
Hello, I just tried chef-client 12.3.0-1 with users-1.8.0 and got SystemStackError : stack level too deep.
In our case, we have user belongs to a few groups but only one ssh key per user.

**Comment by thommay** [comment] 2015-05-19 11:09
@abriel can you post the full stack trace please? and also the latest users cookbook?

**Comment by abriel** [comment] 2015-05-19 11:51
@thommay I am sorry, don't worry. I got the issue https://github.com/chef/chef/issues/3099 . Chef server returns total is 19, but actually there are only 18 matches users. So I get the follwing:
https://chef.coupadev.com/search/users?q=groups:opsnoc%20AND%20NOT%20action:remove&sort=X_CHEF_id_CHEF_X%20asc&start=0
response["rows"].length - 18
response["total"] - 19
https://chef.coupadev.com/search/users?q=groups:opsnoc%20AND%20NOT%20action:remove&sort=X_CHEF_id_CHEF_X%20asc&start=18
response["rows"].length - 0
response["total"] -19
https://chef.coupadev.com/search/users?q=groups:opsnoc%20AND%20NOT%20action:remove&sort=X_CHEF_id_CHEF_X%20asc&start=18
....

I think I should check chef-server somehow. May be do reindex.
Thanks.

**Comment by tas50** [comment] 2017-04-17 23:18
I'm going to close this out since we require Chef 12.5+ now

**Closed by tas50** 2017-04-17 23:18 UTC
Labels: Type: Maintenance
