### ISSUE TITLE
Users not created when databag is encrypted

### ISSUE THREAD

**Issue by sjsadowski** [chef-cookbooks/users#347] opened 2016-08-12 17:26 UTC
### Cookbook version

3.0.0
### Chef-client version

12.13.30
### Platform Details

Linux 3.10.0-327.28.2.el7.x86_64 #1 SMP Wed Aug 3 11:11:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux, CentOS Linux release 7.2.1511 (Core)
### Scenario:

users_manage ignores encrypted databags even if the secret has been specified in client.rb
### Steps to Reproduce:

Create a secret; add the line to client.rb on the client machine. Create a new user databag encrypted with that secret. use users_manage block to create new users specifying the encrypted databag. 
### Expected Result:

Users are created
### Actual Result:

Users are never created

**Comment by tas50** [comment] 2017-04-18 03:50
This is a duplicate of #72. We do need to figure out how to get that in there though. Passwords should be encrypted

**Closed by tas50** 2017-04-18 03:50 UTC
Labels: Type: Bug
